### ISSUE TITLE
Is it possible to suppress at a package level?

### ISSUE THREAD

**Issue by nlongton** [policeman-tools/forbidden-apis#122]
We have some code generated by JavaCC that uses InputStream without a Charset. 
We don't have access to add SuppressForbidden to the code so we'd like to add a package-info.java and suppress warnings for the whole package.
Is this possible?
Thanks
Nigel

**Comment by uschindler** [comment]
You can remove the whole class file from checks with an exclude (depending on your build system). You can do this with the typical Maven/Gradle/Ant like exclude pattern sets based on the file name of the class file. It is part of the documentation: https://jenkins.thetaphi.de/job/Forbidden-APIs/javadoc/, e.g. for Maven: https://jenkins.thetaphi.de/job/Forbidden-APIs/javadoc/check-mojo.html#excludes

In Lucene we removed the broken methods from the generated parse source code with some regular expressions before compiling.
