### ISSUE TITLE
Detect toString()/String.valueOf() calls in AbstractStringBuilder.append(Object)

### ISSUE THREAD

**Issue by kiwiwings** [policeman-tools/forbidden-apis#123]
In Apache POI we have a few rules to prevent calls to non-localized/non-timezoned Methods like Date.toString().
Those are not recognized when AbstractStringBuilder.append(Object) calls them implicit.

Would it make sense to handle those cases?

My current workaround is to convert the calls to call toString() explicitly and eventually ban Abstract/StringBuilder.append(Object).

**Comment by uschindler** [comment]
Hi,
this can't be implemented for several reasons:
- there is no way to detect this from byte code without adding complex state machines to "understand the code".
- It won't work with Java 9 generated bytecode, as string concats no longer use StringBuilders behind the scenes.
