### ISSUE TITLE
Support relative signatureFile location in multimodule Maven projects

### ISSUE THREAD

**Issue by leventov** [policeman-tools/forbidden-apis#126]
forbidden-apis maven plugin doesn't handle relative path properly across multimodule project. Currently I workaround it by configuring
```
<configuration>
    <signaturesFiles>
        <signaturesFile>${session.executionRootDirectory}/codestyle/my-signature.txt</signaturesFile>
    </signaturesFiles>
</configuration>
```

But this approach has limitations, e. g. all maven builds should be done only from a root dir, not from one of submodule dirs.

By contrast, checkstyle handles it's relative config location properly:
```
<configuration>
    <configLocation>codestyle/checkstyle.xml</configLocation>
</configuration>
```

**Comment by uschindler** [comment]
I will check this out. Currently it takes the filename as is and resolves it to CWD or similar. Should be easy to solve.

**Comment by uschindler** [comment]
Hi @leventov 
How do you think resolving should be done? According to current project? This can be done by using `${basedir}` or `${project.basedir}`. If there is any other magic involved, I am not sure if this is really wanted. This code uses the same behaviour like the Maven compiler plugin.

If you want the signatures coming from the parent project, then you should define the plugin in the parent module.

FYI, I looked into the code: I have no way to enforce the resolving path. The signatures files are declared as `File[]` so Maven populates the signatures files attribute on its own and the plugin is just consuming them.

IMHO, another way to handle this would be to define your signatures in the parent project and release them as artifact. You can then refer to the artifact using `<signaturesArtifacts>`  https://jenkins.thetaphi.de/job/Forbidden-APIs/javadoc/check-mojo.html#signaturesArtifacts

**Comment by leventov** [comment]
@uschindler I want it to be resolved as Checkstyle currently does, without any properties referenced, I just configure plugin once in the root pom and it works in all submodules

**Comment by uschindler** [comment]
Can you send you POM snippets or refer to the project that has the problem (e.g., on Github). I know that Apache TIKA and formerly Elasticsearch were doing the same thing: Define in Root POM using `<plugin>`. It should then take the signatures relative to root pom (which is done by maven, not the plugin!).

Are you sure that `${basedir}` does not work?

**Comment by uschindler** [comment]
Sorry, I still don't understand your request, so what's your intention:
- forbiddenapis defined in root pom and one single signatures file is also placed in root folder
- forbiddenapis defined in root pom, but the signatures file should come from same path relative to every subproject? So it should be re-resolved for every thing project?

The difference between forbiddenapis and checkstyle is: Checkstlye defines the path as `String` (which is not recommended according to Maven's guidelines), while forbiddenapis uses `File` instances. For the latter, resolving them is done by Maven. So there is no way to fix this.

**Comment by uschindler** [comment]
Here the difference:
- http://svn.apache.org/viewvc/maven/plugins/tags/maven-checkstyle-plugin-2.17/src/main/java/org/apache/maven/plugin/checkstyle/CheckstyleViolationCheckMojo.java?view=markup#l210
- https://github.com/policeman-tools/forbidden-apis/blob/master/src/main/java/de/thetaphi/forbiddenapis/maven/AbstractCheckMojo.java#L61-L67

**Comment by uschindler** [comment]
Maybe I know what happens in Checkstyle:
http://svn.apache.org/viewvc/maven/plugins/tags/maven-checkstyle-plugin-2.17/src/main/java/org/apache/maven/plugin/checkstyle/exec/DefaultCheckstyleExecutor.java?view=markup#l857

So it searches for files in all projects up to the root. Please read the comment by Olivier Lamy! I will NOT implement anything like that. The configuration is a `File` instance and this `File` instance is located by Maven - not forbiddenapis-plugin, like in any other plugin (JAR plugin, cmpiler plugin,...). What checkstyle does is plain wrong and kept for historical reasons.

I'd recommend to configure signatures files once in root POM and place them in root's folder and refer from root.pom by using `${project.basedir}`.

**Comment by Lonzak** [comment]
Hi,

I have the same problem. If I specify it like this I would need to put the signature files in each project.
```
<signaturesFiles>
<signaturesFile>${project.basedir}/signatures.txt</signaturesFile>
</signaturesFiles>
```
The reason might be that in our multimodule project the aggregator and the parent are separate project.
My workaround is currently like this:
```
<signaturesFiles>
<signaturesFile>${project.basedir}/../parent/signatures.txt</signaturesFile>
</signaturesFiles>
```
However the goal should be that the first solution should work, right?
The maven project setup looks like that:
```

pom.xml (aggregator basically only contains the modules, no parent)
submodule1\pom.xml (parent is the parent below)
submodule2\pom.xml (parent is the parent below)
...
parent-module\pom.xml (which contains the dependencies and plugins like forbiddenapis.
```

So if I now run forbiddenAPIs it throws an exception stating that the signatures in **submodule1\signatures** can not be found.

**Comment by uschindler** [comment]
Hi,
the correct "maven" way to fix this issue is different (forbidden-apis is not the only one having the problem). The checkstyle way is just a bad hack, that won't be implemented here, sorry. It violates Maven's idea and it's also not possible to do in the same way here.

If projects need to share resources via a parent project, the only correct way to do it, is to put the resources into an artifact that is published by the parent project or some extra "build" module. It will contain all the signatures as resources and package them into a JAR file artifact or a simple TXT file artifact.

In the parent pom or any other POM, you refer to the signatures using their maven coordinates: https://jenkins.thetaphi.de/job/Forbidden-APIs/javadoc/check-mojo.html#signaturesArtifacts

**Comment by Lonzak** [comment]
I understand your point and nobody wants the checkstyle approach. I am not too deep into the topic of maven plugins however something is wrong with the path handling of multimodule projects.
Lets illustrate our setup:

pom.xml
submodule1\pom.xml
submodule2\pom.xml
submodule3\pom.xml
maven-parent\pom.xml , signatures.txt <- **The plugin is defined in this pom.xml** but it can't find its own signature.xml next to it...

Now the error I get is:
[ERROR] Failed to execute goal de.thetaphi:forbiddenapis:2.3:check (default) on project submodule1: IO problem while reading files with API signatures.: submodule1/signatures.txt (The file can not be found)

According to that approach I would have to put a signatures.txt in each and every subproject.
_________________________________________________________________________________________________

A solution for me would be  the possibility to specify the signatures directly within the pom. Why use an external file? This would solve the problem for us all. So something like that would help:

<signatures>
      <signature>junit.framework.** @  Some explaination ...</signature>
</signatures>

Or is that already possible?

**Comment by uschindler** [comment]
RTFM: https://jenkins.thetaphi.de/job/Forbidden-APIs/javadoc/check-mojo.html#signatures

It's just a multi-lines text-block (it's not an array). Use a CDATA section if needed.

**Comment by Lonzak** [comment]
No need to get grumpy... Perfekt didn't spot that...

**Comment by uschindler** [comment]
I think I will close the issue, as there are already 2 ways to solve this:
- If you want separate files containing signatures, deploy them as maven artifacts and reuse them using `signaturesArtifacts` config
- Otherwise inline them into the parent POM with `signatures`. You may also use external entities or xinclude (if Maven works with it to have separate files).

Is those 2 solutions enough to fit everybody's needs.

**Comment by uschindler** [comment]
@Lonzak the problem with Maven is that the config of plugins is not inherited with absolute file paths. Every submodule resolves the file objects again and again. If the path is relative, Maven passes a new FileObject accoring to current module path to it.
That's IMHO a bug in the original Maven design, so many people did workarounds.

**Comment by uschindler** [comment]
Here is an example in the tests: https://github.com/policeman-tools/forbidden-apis/blob/master/src/test/antunit/pom-InclExclSuppress.xml#L37-L39

**Comment by Lonzak** [comment]
Thanks for the tests - I did already change it from the signature file to the <signature> block. Problem solved. Thanks for the hint...
