### ISSUE TITLE
Make Java 9 version numbering better and better apply normalization

### ISSUE THREAD

**Issue by uschindler** [policeman-tools/forbidden-apis#130]
Currently Java 9 is translated internally to Java "1.9". The normalization should take care of all versions >=9 and normalize them to no longer use "1." prefix. There are also some places that might break with 2 digit major versions (like 10 or 18).

**Comment by dweiss** [comment]
Some ready to use regexps here? :) http://openjdk.java.net/jeps/223

**Comment by uschindler** [comment]
Not so complicated. The main issue is only to allow many different formats for Java "release/source/target" versions and normalize them, so the lookup of the signatures resources work as expected. Currently all versions are normalized from "major" to "1.major" as a dirty hack.

I have the patch ready that renames the Java 9 signatures files to use plain "9". The parser/normalizer of target/source/release was adapted to normalize only versions < 9 to use "1.major" format.

This is no functionality change, forbiddenapis works as before and accepts same versions, but I am able to rename the signatures resources and the messages printed while loading them are more meaningful:

```
-check-bundled-signatures:
[forbiddenapis] Reading bundled API signatures: jdk-unsafe-9
[forbiddenapis] Reading bundled API signatures: jdk-deprecated-9
[forbiddenapis] Reading bundled API signatures: jdk-internal-9
[forbiddenapis] Reading bundled API signatures: jdk-system-out
[forbiddenapis] Reading bundled API signatures: jdk-reflection
[forbiddenapis] Loading classes to check...
```

Up to java 1.8 / 8 it looks:

```
-check-bundled-signatures:
[forbiddenapis] Reading bundled API signatures: jdk-unsafe-1.8
[forbiddenapis] Reading bundled API signatures: jdk-deprecated-1.8
[forbiddenapis] Reading bundled API signatures: jdk-internal-1.8
[forbiddenapis] Reading bundled API signatures: jdk-system-out
[forbiddenapis] Reading bundled API signatures: jdk-reflection
[forbiddenapis] Loading classes to check...
```

It is just to accept variants like "1.8" but also "8" as target/source/release version.

**Comment by uschindler** [comment]
...i also prepared for the new horrible Dockerlike versioning scheme "18.03" / "18.3", coming March next year.
