### ISSUE TITLE
java 10 is not working due to changed class file format

### ISSUE THREAD

**Issue by jillesvangurp** [policeman-tools/forbidden-apis#136]
I tried to build our software with the newly released jdk10 and the gradle plugin for fobiddenapis is failing:

```
Execution failed for task ':forbiddenApisMain'.
> The class file format of '/Users/jillesvangurp/git/inbot/inbot-eth-client/build/classes/java/main/io/inbot/ethcontracts/InToken$45.class' is too recent to be parsed by ASM.
```

Not super urgent for me since I'm not planning to run this in production but would be nice to get this updated for java 10.

**Comment by uschindler** [comment]
Hi @jillesvangurp, 
there will be a new relaese soon, which also includes deprecated and unsafe signature updates for Java 10. But I have to upgrade to ASM version 6.1 first.
