### ISSUE TITLE
Gradle plugin should have outputs, so that out-of-date checks can work

### ISSUE THREAD

**Issue by trejkaz** [policeman-tools/forbidden-apis#141]
If I run two Gradle builds in a row without changing any code, all the forbidden-apis checks run a second time, because the task has no outputs, making it impossible for Gradle to check whether the outputs are up-to-date with respect to its inputs.

A simple report could be dumped in the build directory which would then have a timestamp, allowing this to work.

**Comment by uschindler** [comment]
The Gradle job has an Output. It refers to is input. The forbidden checks are superseded if the inputs do not change. At least up to now this works fine. Maybe it broke in later Gradle? Which version are you using?

**Comment by trejkaz** [comment]
Gradle 4.7 at the moment, but maybe I should check the latest version of forbidden-apis too, since we are also one version behind.

**Comment by uschindler** [comment]
The latest version (to be released) will also fix a Gradle bug with "custom" sourcesets (where forbiddenapis was not executed, as the setup of sourceset was not recognized). I am not fully sure if the latestreleased version has any gradle changes. Nevertheless, my last tests was with 4.3 and there it worked.
Nevertheless, the idea of having a "dummy zero bytes file" for holding the timestamp of the outputs might be a good idea. We would just need one for every sourceset.

**Comment by uschindler** [comment]
This is how it works currently:
https://github.com/policeman-tools/forbidden-apis/blob/master/src/main/java/de/thetaphi/forbiddenapis/gradle/CheckForbiddenApis.java#L121-L125

...the "classesDirs" property of the task is declared as output - but also as Input: https://github.com/policeman-tools/forbidden-apis/blob/master/src/main/java/de/thetaphi/forbiddenapis/gradle/CheckForbiddenApis.java#L121-L125

So when code is recompiled by a previous task the "output" of forbiddenapis is changed, too. But maybe there is the issue that later versions of gradle get confused if the timestamp goes forward. So there can be several reasons for the "output" trick to break.

**Comment by trejkaz** [comment]
Well, I have re-tested on current version (with current Gradle for the hell of that too) and it seems to work now.

But yeah, that method of specifying the output is rather odd, it makes me think it's pointing the output as the input directories when I read it, which seems like it might even cause the forbiddenApis task to skip execution if some class changed. (The opposite problem to what we had noticed.)

**Comment by uschindler** [comment]
Hi,
no it does not skip it. Because Gradle does not compare in and output timestamps, it just checks if the input changed (it has some hashcode). If you don't specify an output, it won't do that check - that's the reason why it should be specified.
