### ISSUE TITLE
Gradle: support build cache

### ISSUE THREAD

**Issue by sdavids** [policeman-tools/forbidden-apis#146]
Please support Gradle build cache.

https://docs.gradle.org/current/userguide/build_cache.html#sec:task_output_caching_details
https://guides.gradle.org/using-build-cache/

**Comment by uschindler** [comment]
Hi,
the forbidden task has no outputs (yet), so it can't be cached. This may change once we produce reports as a file on disk, but that's not yet possible. See issue #134. 
The task is currently only run if the inputs change, so there won't be any speedup for normal builds. The extension by the build cache is that the input is used as a key for a cache, so if you revert your changes to code, the same results like before the change can be implied. But to report the failures from cache, forbidden needs to save the outputs somewhere.

**Comment by trejkaz** [comment]
I started wondering whether forbidden-apis could be modified to run as a javac plugin so that it necessarily ran as part of producing the classfiles, which would then mean that the cache would only contain already-checked code. 🤔

**Comment by uschindler** [comment]
This is resolved by #155: As the task has currently no output, there's no need to cache anything. The "fake" output was removed by #159 and `upToDateWhen` was fixed to work consistently with other check tasks.

Once we add output files, we will declare them as output and we can enable caching.

**Comment by sebersole** [comment]
FWIW, using 3.2, it is not my experience that these tasks are skipped when sources/classes do not change.  That could be because I spawn multiple tasks rather than relying on the task created by the plugin.

I added a "fake" output to work around this.

I'll dig into your code and see how you configured that.

**Comment by sebersole** [comment]
Just changing outputs I gave the task worked.  From

```
task.classesDirs = project.sourceSets.main.output.classesDirs
task.classpath = project.sourceSets.main.compileClasspath + project.sourceSets.main.runtimeClasspath
```

to 

```
task.classesDirs = project.sourceSets.main.output
task.classpath = configurations.runtimeClasspath + configurations.compileClasspath
```
