### ISSUE TITLE
Include invocations to retrieve Default TimeZone in jdk-unsafe-1.8 ruleset

### ISSUE THREAD

**Issue by aaronols** [policeman-tools/forbidden-apis#151]
While methods that implicitly use the default system timezone are forbidden in the `jdk-unsafe-1.8` ruleset (such as `java.time.LocalDateTime#now()`), it is still possible to explicitly use the default time zone:

```java
LocalDateTime.now(Clock.systemDefaultZone());
LocalDateTime.now(ZoneId.systemDefault());
LocalDateTime.now(TimeZone.getDefault().toZoneId());
```

In my opinion the following invocations should also be forbidden under the `Uses default time zone` rules of the `jdk-unsafe-1.8` ruleset:

```java
java.time.Clock#systemDefaultZone()
java.time.ZoneId#systemDefault()
java.util.TimeZone#getDefault()
```

**Comment by uschindler** [comment]
You can also by default use the default charset or default locale. That's explicitely wanted because the usage is explicit.

The idea behind forbiddenapis is to prevent people from accidentally using defaults. If they are explicit, all is fine.

**Comment by aaronols** [comment]
Ah okay then. My assumption was that explicit usage was forbidden too.

In that case I can just create custom signatures to enforce the rules that make sense for our projects.
Thank you for your time.
