### ISSUE TITLE
New deprecation warnings with Gradle 6.0-rc-1

### ISSUE THREAD

**Issue by huxi** [policeman-tools/forbidden-apis#153]
The following is printed while executing `forbiddenApis` with `--warning-mode all` Gradle option with Gradle 6.0-rc-1 and `de.thetaphi:forbiddenapis:2.7`.

```
Property 'classesDir' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'patternSet' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
```

**Comment by uschindler** [comment]
Hi,
those are not problems, as the correct annotation is there. e.g., classesDoir is only available as a setter for backwards compatibility for older Gradle versions. The "correct" property to use is "classesDirs".

The documentation is not clear what this means after 7.0.

**Comment by uschindler** [comment]
patternSet is a shadow of includes / exlcudes. It's there to implement an interface. I have to figure out how other Gradle-internal tasks handle this. Maybe there is another annotation to prevent this warning from appearing (e.g. `@AlreadyDefinedAsInputAndIKnowWhatIAmDoing`)

**Comment by uschindler** [comment]
Looks like https://docs.gradle.org/6.0-rc-1/javadoc/org/gradle/api/model/ReplacedBy.html is the way to go for the first example.

**Comment by uschindler** [comment]
Unfortunately it's since Gradle 5.4, so it can't be added, sorry! But https://docs.gradle.org/6.0-rc-1/javadoc/org/gradle/api/tasks/Internal.html can be used as workaround.
