### ISSUE TITLE
maven central pom download fails due to https requirements

### ISSUE THREAD

**Issue by mkmaier** [policeman-tools/forbidden-apis#171]
When trying to build 3.0 locally, the pom download failed, because it used the unsafe default maven central url (probably due to using maven 2.0).
This should fix the pom download in build.xml, but there might be other places where the repo needs to be specified:

    -    <artifact:pom id="maven.deploy.pom" file="${maven.deploy.pom}"/>
    +    <artifact:pom id="maven.deploy.pom" file="${maven.deploy.pom}">
    +      <remoteRepository refid="mvn.maven-central.backup" />
    +    </artifact:pom>

**Comment by uschindler** [comment]
Hi,
I was reviewing most places with that issue, but `<artifact:pom/>` seems to be fallen under the radar. I am quite sure that I did a full bootstrap with empty Maen Cache and Ivy cache, but I will check this again!

What exactly failed? Can you post the full Maven log?

Thanks for reporting.

**Comment by uschindler** [comment]
It would really be good, if Maven releases a "bugfix" Maven Ant Tasks, because this causes headaches also in Apache Lucene and other projects using those to deploy their artifacts to Maven.

**Comment by uschindler** [comment]
I am quite sure this is the only remaining problematic part. The `artifact:deploy` tasks are no issue. And `artifact:mvn` got a special bootstrapping already.

**Comment by uschindler** [comment]
Hi,

> What exactly failed? Can you post the full Maven log?

I assume it fails to download the parent Sonatype POM?

**Comment by uschindler** [comment]
I was able to reproduce this:

```
-maven-setup:
    [mkdir] Created dir: C:\Users\Uwe Schindler\Projects\lucene\forbidden-apis\forbidden-apis\build\maven
     [copy] Copying 3 files to C:\Users\Uwe Schindler\Projects\lucene\forbidden-apis\forbidden-apis\build\maven
[artifact:pom] Downloading: org/sonatype/oss/oss-parent/9/oss-parent-9.pom from repository central at http://repo1.maven.org/maven2
[artifact:pom] Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
[artifact:pom] [WARNING] Unable to get resource 'org.sonatype.oss:oss-parent:pom:9' from repository central (http://repo1.maven.org/maven2): Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
[artifact:pom] An error has occurred while processing the Maven artifact tasks.
[artifact:pom]  Diagnosis:
[artifact:pom]
[artifact:pom] Unable to initialize POM pom-deploy.xml: Cannot find parent: org.sonatype.oss:oss-parent for project: de.thetaphi:forbiddenapis:maven-plugin:3.1-SNAPSHOT for project de.thetaphi:forbiddenapis:maven-plugin:3.1-SNAPSHOT
[artifact:pom] Unable to download the artifact from any repository
[artifact:pom]
```

I will commit a fix to master branch.

**Comment by uschindler** [comment]
I will add a mental todo: Use https://maven.apache.org/resolver-ant-tasks/ instead. This looks like it also allows to install and deploy files.
