### ISSUE TITLE
[Wiki] Example for suppressions

### ISSUE THREAD

**Issue by bmhm** [policeman-tools/forbidden-apis#172]
There are no PRs for the WIKI, so feel free to merge those changes yourself.

https://github.com/bmhm/forbidden-apis-wiki/commit/0a0c00c8e8c768198e3e559735895f62d45ca8de

You can check out your wiki, add my repo as a remote manually, merge in the commit above and push it to origin again.

**Comment by uschindler** [comment]
I merged this: https://github.com/policeman-tools/forbidden-apis/wiki/MavenUsage/0a0c00c8e8c768198e3e559735895f62d45ca8de

Thanks.

IMHO, we can improve this by just explaining to use `**.Generated` (wildcard, `**` is any package). I think we can also put this into Gradle instructions.

I will hack a bit once I have more time. Thanks anyways!
