### ISSUE TITLE
Add `DataOutput.writeBytes(String)` (and overrides)

### ISSUE THREAD

**Issue by Marcono1234** [policeman-tools/forbidden-apis#185]
Hello,
[`DataOutput.writeBytes(String)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/DataOutput.html#writeBytes(java.lang.String)) and its overrides only writes the low byte of each character, ignoring the high byte.
Should it be added to the list of forbidden signatures (for Java 7)?

**Comment by uschindler** [comment]
Hi thanks for this issue. This is indeed needed.

I'll add to the signatures. It is not needed to add the overrides because of inheritance from this interface.

**Comment by uschindler** [comment]
I also added the complement `DataInput.readLine()` which has exactly the same problem. `DataInput.readBytes()` does not exist.
