### ISSUE TITLE
Add support for Java 19

### ISSUE THREAD

**Issue by Danny02** [policeman-tools/forbidden-apis#204]
Hi,

I just tried upgrading my project to Java 19 and this plugin does not seem to support it. It fails on a class with the error:
`The class file format of '.../X.class' is too recent to be parsed by ASM.`

**Comment by uschindler** [comment]
Hi,

Sure. Give me a few days to zu update the ASM library. I have not yet checked their release status.

Generally the Forbiddenapis update is released a few days/weeks after the java update, but thanks for the reminder.

Uwe

**Comment by uschindler** [comment]
See PR #205 which upgrades ASM.

**Comment by Danny02** [comment]
Hi, thanks for the feedback. I of course did not want hustle you 😄.
I just saw one pull request which was Java19 related which was closed.
Wasn‘t sure if this was on your roadmap.

Uwe Schindler ***@***.***> schrieb am Fr. 23. Sept. 2022 um
21:39:
