### ISSUE TITLE
Commons IO by dependencies

### ISSUE THREAD

**Issue by GoogleCodeExporter** [policeman-tools/forbidden-apis#21]
```
It would be nice if the commons-io-unsafe bundle would take the version from 
the dependencies, so you don't have to care about it, when upgrading.


```

Original issue reported on code.google.com by `burber...@gmail.com` on 22 Nov 2013 at 8:45

**Comment by uschindler** [comment]
I will close this issue: I looked at the code while implementing signatures loaded from Maven artiacts. The commons-io stuff could get a special case. But I think it is much easier for the user to define a property in the (master-)POM and use it for both the dependency and also the forbidden plugin.
