### ISSUE TITLE
Add HttpResponse.BodyHandlers.ofFile(Path) to banned method lists (buggy)

### ISSUE THREAD

**Issue by dweiss** [policeman-tools/forbidden-apis#214]
Eh. Perhaps worth adding to forbidden method list with a comment saying it's likely buggy in whatever JDK one is using:
https://bugs.openjdk.org/browse/JDK-8299015

**Comment by uschindler** [comment]
Hey, let me see. Of course it will be fixed in 21, so we need some trick there to undo the addition (it reads signatures incrementally).

I added this method to the Java 11 unsafe methods. I will think about a solution for 21.

**Comment by uschindler** [comment]
See this commit: 020f4cbbd1768f9c1e3b591bdb30903eaab767fa
