### ISSUE TITLE
(Gradle) How to avoid creation of a forbiddenApisTest task

### ISSUE THREAD

**Issue by guillerodriguez** [policeman-tools/forbidden-apis#217]
I would like to use forbiddenApis to check for API violations in the main sourceSet, but not in the test sourceSet. Is there a way to tell forbiddenApis to ignore specific sourceSets?

I tried to leave the default signatures empty for the test sourceSet but then I get a "No signatures were added to task" error.

**Comment by uschindler** [comment]
Just disable the task.

**Comment by guillerodriguez** [comment]
Indeed. Thanks!
