### ISSUE TITLE
Remove HttpResponse.BodyHandlers.ofFile(Path) from banned method list in Java 21 signatures

### ISSUE THREAD

**Issue by uschindler** [policeman-tools/forbidden-apis#225]
Followup of #214, this method must be removed in signatures files for Java 21.

**Comment by kwin** [comment]
Actually the fix is even backported to 17.0.7: https://bugs.openjdk.org/browse/JDK-8299353

**Comment by uschindler** [comment]
That's fine, but it is still not recommend to use that function. Because if you develop a library you do not know which version java runs on.
