### ISSUE TITLE
Provide option to enabled DEBUG level logging when using the CLI

### ISSUE THREAD

**Issue by mark-vieira** [policeman-tools/forbidden-apis#226]
As discussed in https://github.com/elastic/elasticsearch/issues/94773 it would be helpful to be able to opt into more verbose logging when using the CLI, in addition to the existing option for the build tool plugins.

**Comment by uschindler** [comment]
See the new PR #227.
I am doing some testing, but it restores previous functionality if you start the CLI tool with `--debug` command line option. There are only slight changes:
- Prefix of message is "DEBUG".
- Message comes on stdout, not stderr (as it is now <=INFO).
- The suffix of message was removed ("please fix classpath").

**Comment by uschindler** [comment]
In Opensearch this would need to be then adapted: https://github.com/opensearch-project/OpenSearch/blob/b1cf2d144ebac899bcae9880ee51728df397b5c0/buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java#L82-L84

In Elasticserach should be same.

**Comment by uschindler** [comment]
Does anybody has an idea why the forbiddenapis JAR is mentioned 3 times in dependencies. Most crazy was that it is also part of Java source code!?! @reta

**Comment by reta** [comment]
@uschindler I do not know the history but here are my guesses:
 - `ThirdPartyAuditPrecommitPlugin` needs the `forbiddenApis` so it adds all the time
 -  the `buildSrc` uses `forbiddenApis` directly (since it cannot use `ThirdPartyAuditPrecommitPlugin` as it builds it)
 -  for `buildSrc/src/testKit/thirdPartyAudit/build.gradle`, I think it not needed (should be provided by `ThirdPartyAuditPrecommitPlugin`)

**Comment by uschindler** [comment]
> @uschindler I do not know the history but here are my guesses:
> 
> * `ThirdPartyAuditPrecommitPlugin` needs the `forbiddenApis` so it adds all the time

That's the craziest to me. I am fine with it, but the version number should not be hardcoded there, maybe it should be a global property (like Lucene uses, it has all helper versions in a map on `project.ext`.

> * the `buildSrc` uses `forbiddenApis` directly (since it cannot use `ThirdPartyAuditPrecommitPlugin` as it builds it)

This is to execute the standard plugin-provided forbiddenApis (`gradlew forbiddenApis`).

> * for `buildSrc/src/testKit/thirdPartyAudit/build.gradle`, I think it is not needed (should be provided by `ThirdPartyAuditPrecommitPlugin`)

I can try to remove that one, I had the same idea.

**Comment by mark-vieira** [comment]
> Does anybody has an idea why the forbiddenapis JAR is mentioned 3 times in dependencies. Most crazy was that it is also part of Java source code!?! @reta

The main two are as @reta mentiones. First the plugin adds it as a default dependency and also by the build logic itself. It _could_ read this from the same place used by the build in theory so this isn't duplicated.

**Comment by uschindler** [comment]
Release is coming later today.

**Comment by uschindler** [comment]
Release 3.5.1 is on plugin portal, Maven takes a bit longer. I will update the Opensearch PR once its on all repos.

**Comment by reta** [comment]
> Release 3.5.1 is on plugin portal, Maven takes a bit longer. I will update the Opensearch PR once its on all repos.

Thanks a lot @uschindler !

**Comment by mark-vieira** [comment]
Thanks @uschindler!
