### ISSUE TITLE
Clarify Maven configuration parameter "includes" and "excludes"

### ISSUE THREAD

**Issue by kwin** [policeman-tools/forbidden-apis#228]
Currently the javadoc of `includes` and `excludes` (https://github.com/policeman-tools/forbidden-apis/blob/beaaa9c362d7ab3e95848f769fd15443373e4cb4/src/main/java/de/thetaphi/forbiddenapis/maven/AbstractCheckMojo.java#L198-L214) only refer to generic pattern. It should be clarified that this is not a regular expression pattern but an Ant-style one (https://ant.apache.org/manual/dirtasks.html#patterns). Additionally it should be clarified that this is matched against the relative path of the class file (relative to `build.outputDirectory`, https://maven.apache.org/ref/3.9.1/maven-model/maven.html#build).

Those javadocs are used to generate the Maven site documentation at https://jenkins.thetaphi.de/job/Forbidden-APIs/javadoc/check-mojo.html#excludes.

**Comment by uschindler** [comment]
I will add a note to clarify this. For directory patterns the use of ant include/exclude patterns is common in Gradle/Ant world so I assumed that in Maven it is also common.

**Comment by kwin** [comment]
I am preparing a PR clarifying this and also upgrading to the newest m-plugin-p allowing you to render links to javadoc in Maven sites for plugins.
