### ISSUE TITLE
Consider JEP 400  for jdk-unsafe Bundled Signatures

### ISSUE THREAD

**Issue by kwin** [policeman-tools/forbidden-apis#231]
It would be nice to add a link to https://openjdk.org/jeps/400 in https://github.com/policeman-tools/forbidden-apis/wiki/BundledSignatures#bundled-signatures-files as Java18+ always uses UTF-8 as default charset. Therefore using APIs relying on the default charset is safe in classes targeting Java 18 or above. The signatures need to be adjusted accordingly: https://github.com/policeman-tools/forbidden-apis/blob/main/src/main/resources/de/thetaphi/forbiddenapis/signatures/jdk-unsafe-18.txt

**Comment by uschindler** [comment]
Hi,
this is still incorrect to rely on default charset. It is correct that Java 18+ has UTF-8 as default charset, but it can still be changed.

Therefor the signtures files won't change as the underlying problem still exists.
