### ISSUE TITLE
Remove jdk.jfr from non portable exceptions list

### ISSUE THREAD

**Issue by dreab8** [policeman-tools/forbidden-apis#234]
it seems JFR is part of the SE https://docs.oracle.com/en/java/javase/11/docs/api/jdk.jfr/module-summary.html so it should not be reported as non portable

**Comment by uschindler** [comment]
Hi,
please read the text in root of Javadocs: https://docs.oracle.com/en/java/javase/11/docs/api/index.html

> This document is divided into two sections:
>
> [Java SE](https://docs.oracle.com/en/java/javase/11/docs/api/index.html#JavaSE)
> The Java Platform, Standard Edition (Java SE) APIs define the core Java platform for general-purpose computing. These APIs are in modules whose names start with java.
[JDK](https://docs.oracle.com/en/java/javase/11/docs/api/index.html#JDK)
The Java Development Kit (JDK) APIs are specific to the JDK and will not necessarily be available in all implementations of the Java SE Platform. These APIs are in modules whose names start with jdk.

All modules with a name "java.*" are core Java platform. All starting with "jdk.*" fall under "will not necessarily be available". So it is not portable.
