### ISSUE TITLE
Clarify what retention scope is required for forbiddenapis suppression annotations

### ISSUE THREAD

**Issue by laurentgo** [policeman-tools/forbidden-apis#243]
Forbiddenapis provides a way to suppress violations by using annotations. However the documentation does not specify what retention scope the annotation should use to be detected by forbiddenapis

From the code itself it seems it should be `CLASS` or `RUNTIME`, which makes sense since `SOURCE` means the annotation is not present in the binary output. But it means the example in https://github.com/policeman-tools/forbidden-apis/wiki/MavenUsage is misleading as `javax.*.Generated` annotations have a `SOURCE` [retention](https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/javax/annotation/processing/Generated.html).

**Comment by uschindler** [comment]
Hi,
sorry for the late response. Source retention can't be detected as it is no longer in the class files.

So both runtime and class works.

**Comment by uschindler** [comment]
P.S.: The documentation is there for all three types of build systems (see . It may miss in the Wiki, will check later):

Latest doc: https://jenkins.thetaphi.de/job/Forbidden-APIs/javadoc/

**Comment by uschindler** [comment]
I fixed the documentation in Wiki. This was a pull request which was not fully checked: 36ea3787919e2fe437c64c3c5947f05b08c743a4
