### ISSUE TITLE
compatibility with Gradle 9.x

### ISSUE THREAD

**Issue by sdavids** [policeman-tools/forbidden-apis#245]
```shell
> Task :forbiddenApisMain
The org.gradle.api.plugins.JavaPluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.6/userguide/upgrading_version_8.html#java_convention_deprecation
The org.gradle.api.plugins.Convention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.6/userguide/upgrading_version_8.html#deprecated_access_to_conventions
```

gradle/libs.versions.toml
```toml
[plugins]
forbiddenapis = "de.thetaphi.forbiddenapis:3.6"
```

**Comment by uschindler** [comment]
No idea where this class is referenced. It's just standard plugin code.

https://github.com/policeman-tools/forbidden-apis/blob/6a4204546e7e56001ec96ef1c7477d975ab26e56/src/main/groovy/de/thetaphi/forbiddenapis/gradle/ForbiddenApisPlugin.groovy

**Comment by sdavids** [comment]
https://docs.gradle.org/8.6/userguide/upgrading_version_8.html#java_convention_deprecation

https://github.com/policeman-tools/forbidden-apis/blob/6a4204546e7e56001ec96ef1c7477d975ab26e56/src/main/groovy/de/thetaphi/forbiddenapis/gradle/ForbiddenApisPlugin.groovy#L50

**Comment by uschindler** [comment]
I am not sure if I have an idea how to fix this. So it could be that I won't have time to fix this for next version.

Uwe

**Comment by uschindler** [comment]
I will delay changes to after the Java 22 compatibility release. Sorry. I don't feel this is too urgent.

**Comment by uschindler** [comment]
Hi,
I fixed the problem in this PR: #247

**Comment by sdavids** [comment]
Will verify with `3.7`.

**Comment by uschindler** [comment]
Thanks! I did this already with Jenkins: https://jenkins.thetaphi.de/job/Forbidden-APIs-testonly-GradleLatest-Linux/119/console

**Comment by uschindler** [comment]
In addition I also changed the code to fetch sourceSets directly from Java extension, if available (after Gradle 7.1). Tis should make it future proof. Normally there should also be a warning poping up, but it isn't.

**Comment by uschindler** [comment]
See 068b0ca72b4bdc5054467e8f1b5a36c8b98694bf

**Comment by uschindler** [comment]
v9.7 was released a minute ago.

**Comment by sdavids** [comment]
verified with v3.7
