### ISSUE TITLE
Review changes caused by JIGSAW packaging and fix class loading and class traversal issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [policeman-tools/forbidden-apis#39]
```
See http://openjdk.java.net/jeps/220

In future, the bootclasspath of Java will no longer be rt.jar and the URLs 
returned by Class.getResource() will no longer be "jar:" URLs. We have to fix 
the code that does classpath traversal to respect this.

This also affects the code that creates the deprecated lists from rt.jar.

It is currently unknown if there will be a good way to enumerate all class 
files in a classpath...
```

Original issue reported on code.google.com by `uwe.h.schindler` on 31 Oct 2014 at 9:19

**Comment by uschindler** [comment]
Detecting if a class in Java 9 is coming from the runtime is damn simple:
`"jrt".equalsIgnoreCase(loader.getResource("java/lang/Object.class").getProtocol())`
"jrt" means Java runtime and is reserved for all resources coming from the runtime, so isRuntime is very easy to detect. No bullshit needed like getting bootclasspath through RuntimeMXBean.
