### ISSUE TITLE
Support for checking single file instead of whole directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [policeman-tools/forbidden-apis#47]
```
Based on input parameters 
(https://code.google.com/p/forbidden-apis/wiki/CliUsage) I see that I can 
provide directory with source code and all files fill be examined. However I 
think it would be nice to add support for forbidden-apis to 
https://github.com/TouK/sputnik and for this I need to be able to scan single 
or more selected files instead of whole directory.

Thanks,
Damian
```

Original issue reported on code.google.com by `damian.p...@gmail.com` on 30 Jan 2015 at 10:00

**Comment by uschindler** [comment]
In general, it is also possible with the CLI tool to check single files. I also added a test about this. You can pass a directory name with `--dir`, but as second parameter a ANT-like pattern for `--includes <pattern>`. If the pattern is a single file name, you have all you need.
I will close this issue now.
