### ISSUE TITLE
Add unsafe signatures for Java 9/10/11/12/13

### ISSUE THREAD

**Issue by uschindler** [policeman-tools/forbidden-apis#49]
Once Java 9 comes out...

**Comment by Sanne** [comment]
This could be closed?

**Comment by uschindler** [comment]
I wanted to check it again, so I kept it open. But newer Java versions no longer add locale-less and charset-less methods.

**Comment by bmhm** [comment]
I think this can be closed. ;-)

**Comment by uschindler** [comment]
Yes, this was more a placeholder. Newer Java versions at least no longer add locale/charset/timezone sensitive methods, so updates are not needed.
