### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by kwin** [policeman-tools/forbidden-apis#61]
Currently the only error message is something like
```
[INFO] Scanning for API signatures and dependencies...
[ERROR] Forbidden method invocation: java.text.SimpleDateFormat#<init>(java.lang.String) [Uses default locale]
[ERROR]   in <some.class.Name>(<Name>:<lineNumber>)
```

It would be good if (optionally) the link towards the blog post at http://blog.thetaphi.de/2012/07/default-locales-default-charsets-and.html could be given out. That would give further information why this is considered bad practice. This would be especially helpful for developers not really familiar with this plugin in order to help them understand what they did wrong and why.

**Comment by uschindler** [comment]
Hi,
we should not bloat the error messages with this information, although we could do this (we would need to update the error messages in the bundled signatures files). A possibility could maybe to add a short link.

Another option would be to add some informative line at start of plugin.

**Comment by uschindler** [comment]
Closed because of no response.

**Comment by kwin** [comment]
I didn't really see a question, therefore there was no response from my side. All suggested options from above would be fine with me, but at least some information (even if this information must be enabled in the Maven configuration) would be great.
