### ISSUE TITLE
Derive CLI parameters from maven pom.

### ISSUE THREAD

**Issue by thomasdarimont** [policeman-tools/forbidden-apis#80]
It would b helpful if the CLI could derive the necessary parameters like classpath 
and class folder from a given maven pom.xml.

Same could apply to a gradle file / ivy dependency listing.

**Comment by uschindler** [comment]
The CLI is a command line tool and has no dependency or use of Maven/Ant/Ivy. So there is no way to allow this. If you want to use Maven, do it with Maven.

**Comment by uschindler** [comment]
I am closing this, because the CLI tool cannot use Maven/Gradle config files, as it has no dependency on Maven or Gradle. Adding such a dependency is not going to happen.
