### ISSUE TITLE
Add unsafe signatures for ResourceBundle

### ISSUE THREAD

**Issue by trejkaz** [policeman-tools/forbidden-apis#89]
These two methods use the default locale and for some reason are missing from the list:

    java.util.ResourceBundle#getBundle(java.lang.String)
    java.util.ResourceBundle#getBundle(java.lang.String, java.util.ResourceBundle$Control)

Maybe they were omitted deliberately? But I would like to at least see a comment saying why. :)

**Comment by uschindler** [comment]
Hi @trejkaz,
I will check those out. They are an oversight, for sure. The unsafe signatures is manual work and there may be many others that are missing!

**Comment by uschindler** [comment]
Thanks, I committed the 2 new signatures to the JDK 1.6+ signatures file
