### ISSUE TITLE
Maybe ban StringBufferInputStream

### ISSUE THREAD

**Issue by trejkaz** [policeman-tools/forbidden-apis#93]
I just ran across a usage of `java.io.StringBufferInputStream` in our code and am facepalming pretty hard.

To summarise what `StringBufferInputStream`, basically it takes each char and casts to byte. So it will produce the right behaviour as long as the string contains only Latin-1, but for anything else it produces the wrong results.

So I think it's safe to say that nobody should want this behaviour, but on the other hand it is at least equally wrong irrespective of what your charset is set to... ;)

So is this the sort of thing that should be banned? I'll be banning it here in any case. :)

**Comment by uschindler** [comment]
I was about to ban it, but it does what its docs say. So it is not the classical default charset issue. There are more API that are documented to only work with latin1.

Other problematic apis are also URL#getPath and similar. Broken if you use them incorrect, but they do what is documented and have their use cases.

**Comment by trejkaz** [comment]
It is definitely a different issue to the default charset thing. It's a different class of bug, really ("gives the wrong result for some inputs"), so I wasn't sure whether it qualified or not.

I think I'm banning it here regardless because I can't see that valid use case in this particular situation.

(Along similar -- but much less evil -- lines we have a bit of an open debate here about those new methods in `Files` which default to UTF-8. They behave the same irrespective of your default charset. And they will even work for all strings! But at some point in the past, ISO-8859-1 worked for "all strings" too. :/)

**Comment by centic9** [comment]
I will also ban those and only use them with a suppression if really intended. 

Things like these could go into a "you might want to additionally ban" section in the wiki or a "potential forbid" file.

**Comment by uschindler** [comment]
I think all this is open to the user. I'd don't like to add some "default" file for this, because preferences about using / not-using APIs is project-specific. E.g., Elasticsearch has a quite huge forbidden list, but everything inside is somehow specific to the project.
